name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ankushsinghgandhi
          POSTGRES_PASSWORD: password123
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: > 
          --health-cmd="pg_isready -U ankushsinghgandhi" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Set DATABASE_URL for the test database
    - name: Set DATABASE_URL environment variable
      run: echo "DATABASE_URL=postgresql://ankushsinghgandhi:password123@localhost:5432/test_db" >> $GITHUB_ENV

    - name: Run tests
      run: |
        pytest
